package models;

/**
 * Основные счётчики объектов группы
 */
public enum GroupCounterType {
    ADS_TOPICS,
    BLACK_LIST,
    CATALOGS,
    DELAYED_TOPICS,
    FRIENDS,
    JOIN_REQUESTS,
    LINKS,
    MAYBE,
    MEMBERS,
    MODERATORS,
    MUSIC_TRACKS,
    NEW_PAID_TOPICS,
    OWN_PRODUCTS,
    PAID_MEMBERS,
    PAID_TOPICS,
    PHOTOS,
    PHOTO_ALBUMS,
    PINNED_TOPICS,
    PRESENTS,
    PRODUCTS,
    PROMO_TOPICS_ON_MODERATION,
    SUGGESTED_PRODUCTS,
    SUGGESTED_TOPICS,
    THEMES,
    UNPUBLISHED_TOPICS,
    VIDEOS;
}
